# Model Configuration
# Available providers: openai | zhipu | anthropic | gemini | dummy
#
# Option 1: OpenAI GPT-5 (highest quality, higher cost)
# provider: openai
# model: gpt-5-2025-08-07
#
# Option 2: Z.ai GLM-4.6 (coding plan model) - ACTIVE
provider: zhipu
model: glm-4.6
#
temperature: 0.2
max_output_tokens: 800
dry_run: true             # set to false for real control
overlay:
  enabled: false
  duration_ms: 250
  always_on:
    enabled: false
    radius: 18
    poll_ms: 80
loop:
  max_steps: 50
  min_interval_ms: 200    # Reduced for Windows native performance
screenshot:
  width: 1280
  quality: 75             # Slightly higher for better OCR accuracy
throttle_ms: 0
hotkeys:
  pause: "ctrl+alt+p"
  stop: "ctrl+alt+s"

windows_uia:
  enabled: false           # Disabled - Phase 2 feature needs implementation fixes
  timeout_ms: 1500
  prefer_uia: false

ocr:
  enabled: false           # Disabled - Phase 2 feature (requires Tesseract)
  language: eng
  min_score: 0.70
  psm: 6
  oem: 3
  region: null             # [left,top,width,height] or null for full screen
