# Windows-Optimized Model Configuration
# Available providers: openai | zhipu | anthropic | gemini
# Configuration focused exclusively on Windows-supported vision providers
#
# ⚠️ CRITICAL: For Zhipu, always use model "glm-4.5v" (the vision model)
# ⚠️ DO NOT change ZHIPU_BASE_URL - it MUST be https://api.z.ai/api/coding/paas/v4
#
# Windows-Only Vision Provider Options:
#
# Option 1: Z.ai GLM-4.5V (vision + coding model) - ACTIVE
# Use a dummy provider for offline testing without API keys
provider: zhipu
model: glm-4.5v
#
# Option 2: OpenAI GPT-5 (highest quality, higher cost)
# provider: openai
# model: gpt-5-2025-08-07
#
# Option 3: OpenAI GPT-4o (balanced performance)
# provider: openai
# model: gpt-4o
#
# Option 4: Anthropic Claude (vision capable)
# provider: anthropic
# model: claude-3-5-sonnet-20241022
#
# Option 5: Google Gemini (vision capable)
# provider: gemini
# model: gemini-1.5-pro
temperature: 0.2
max_output_tokens: 2000   # Increased to prevent JSON truncation
dry_run: false            # LIVE MODE: execute real mouse/keyboard actions
overlay:
  enabled: true            # ENABLED for visual debugging
  duration_ms: 1000         # Show crosshair for 1 second
  always_on:
    enabled: false
    radius: 18
    poll_ms: 80
loop:
  max_steps: 50
  min_interval_ms: 200    # Reduced for Windows native performance
screenshot:
  width: 1280
  quality: 75             # Slightly higher for better OCR accuracy
throttle_ms: 0
hotkeys:
  pause: "ctrl+alt+p"
  stop: "ctrl+alt+s"

windows_uia:
  enabled: false           # Disabled - Phase 2 feature needs implementation fixes
  timeout_ms: 1500
  prefer_uia: false

ocr:
  enabled: false           # Disabled - Phase 2 feature (requires Tesseract)
  language: eng
  min_score: 0.70
  psm: 6
  oem: 3
  region: null             # [left,top,width,height] or null for full screen

verify:
  wait_ms: 180
  save_images: true
  click_delta_threshold: 0.015
  double_click_delta_threshold: 0.02
  right_click_delta_threshold: 0.015
  type_delta_threshold: 0.01
  scroll_delta_threshold: 0.03
  drag_delta_threshold: 0.03
  retry:
    enabled: true
    max_retries: 1
    jitter_px: 3
    enlarge_factor: 1.5
