# Model Configuration
# Available providers: openai | zhipu | anthropic | gemini | dummy
#
# Option 1: OpenAI GPT-5 (highest quality, higher cost)
provider: openai
model: gpt-5-2025-08-07
#
# Option 2: Z.ai GLM-4.5v (lower cost, good quality)
# provider: zhipu
# model: glm-4.5v
#
temperature: 0.2
max_output_tokens: 800
dry_run: true             # set to false for real control
overlay:
  enabled: false
  duration_ms: 250
loop:
  max_steps: 50
  min_interval_ms: 400
screenshot:
  width: 1280
  quality: 70
throttle_ms: 0
hotkeys:
  pause: "ctrl+alt+p"
  stop: "ctrl+alt+s"
